Microsoft/spring-cloud-playground

.travis.yml
=> Add travisCI config for repo, #1.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/GeneratorMetadata.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/GeneratorMetadataBuilder.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/GeneratorProperties.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/Link.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/MetadataElement.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/ModulePropertiesResolver.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/Repository.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/SimpleGeneratorMetadataProvider.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/SingleSelectCapability.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/TextCapability.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/Type.java, src/main/java/com/microsoft/azure/springcloudplayground/metadata/TypeCapability.java
* Rewrite lambda with filter
* Add new line separate code block
* Replace Getter and Setter with lombok
=> Code clean for the rest of metadata module

pom.xml, src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/util/TelemetryProxy.java, src/main/resources/ApplicationInsights.xml, src/main/resources/META-INF/project.properties, src/main/resources/application.yml, src/main/resources/static/js/start.js, src/main/resources/templates/home.mustache
* Add event for website access.
* Add event for project generate.
* Add event for account login.
=> Add telemetry bi to azure spring cloud website, #5.

src/main/java/com/microsoft/azure/springcloudplayground/autoconfigure/DefaultGeneratorMetadataProvider.java
* use static final field to hold this data, #14.
=> Eliminate unnecessary http request, #14.

pom.xml
* Only filter project.properties.
=> Fix defect of resouce filter.

pom.xml, src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectRequest.java, src/main/java/com/microsoft/azure/springcloudplayground/service/ServiceModule.java, src/main/resources/static/css/customize.css, src/main/resources/templates/docker/docker-compose.yml, src/main/resources/templates/home.mustache
* Allow customize service port from website.
* Detect invalid port configuration and provide default port.
=> Add configurable port to website, #3.

src/main/resources/templates/home.mustache
* GA will detect all events, as well as unique users with events.
=> Add event tracking for project generation from GA.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java
=> fix incorrect service name

src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/MicroService.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/SimpleProjectRequest.java, src/main/resources/templates/parent-pom.xml
* format some code.
* create one post method.
* build the root directory with pom.xml.
=> Use SimpleProjectRequest for RESTful post request

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/ServiceMetadata.java, src/main/resources/templates/parent-pom.xml, src/main/resources/templates/properties/bootstrap-non-config-server.yml
=> Generate microservices directory.

.travis.yml
=> Use master branch for deployment.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java
=> Fix one defect of access resource in jar package.

src/main/resources/templates/azure-storage/StorageController.java
=> Fix bug of 404 error to localhost:8080/storage/, fix #79.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/resources/templates/azure-sql-server/application.properties, src/main/resources/templates/azure-sql-server/data.sql, src/main/resources/templates/azure-sql-server/schema.sql
=> Add sql file to resource for sql module, fix #83.

src/main/java/com/microsoft/azure/springcloudplayground/service/ServiceMetadata.java, src/main/resources/application.yml, src/main/resources/static/js/start.js, src/main/resources/templates/config-infra-service.mustache
=> select infra modules by default and cannot delete

src/main/java/com/microsoft/azure/springcloudplayground/service/Service.java, src/main/resources/templates/docker/kubernetes.yml
=> Fix kubernates failure for property update, fix #107.

src/main/resources/application.yml, src/main/resources/templates/parent-pom.xml
=> Add azure-dependencies-pom to project generated.

src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectRequest.java, src/main/java/com/microsoft/azure/springcloudplayground/security/WebSecurityConfig.java, src/main/resources/static/js/start.js, src/main/resources/templates/config-azure-service.mustache, src/main/resources/templates/home.mustache
* Add modal to allow user to configure the github repository name.
* Add report issue link
=> GitHub repo config (refs #130)

src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/github/GithubApiWrapper.java, src/main/java/com/microsoft/azure/springcloudplayground/github/GithubOperator.java, src/main/java/com/microsoft/azure/springcloudplayground/security/GithubLoginSuccessHandler.java, src/main/java/com/microsoft/azure/springcloudplayground/security/WebSecurityConfig.java
=> Add telemetry for playground websit.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/java/com/microsoft/azure/springcloudplayground/github/GithubOperator.java
=> Add some logs for push process.

src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/security/GithubLoginSuccessHandler.java
=> fix potential GDPR risk.

src/main/java/com/microsoft/azure/springcloudplayground/github/GitDataFileBlobCreator.java, src/main/java/com/microsoft/azure/springcloudplayground/github/GithubApiWrapper.java, src/main/java/com/microsoft/azure/springcloudplayground/github/GithubOperator.java, src/main/java/com/microsoft/azure/springcloudplayground/github/gitdata/GitDataFileBlob.java
* Faster our repository creation during from 55+s to 12+s in average.
=> Add concurrent POST request to blob API, fix #147.

src/main/java/com/microsoft/azure/springcloudplayground/github/GithubRepository.java
=> Remove homepage link of generated repo.

README.md
=> Fix one 404 of Azure dev space in README.md

src/main/java/com/microsoft/azure/springcloudplayground/github/GithubOperator.java
=> Keep fixed thread pool for all operators, fix #163.

src/main/resources/application.yml, src/main/resources/templates/azure-cosmosdb/CosmosdbController.java, src/main/resources/templates/azure-eventhub-binder/SinkExample.java, src/main/resources/templates/azure-eventhub-binder/SourceExample.java, src/main/resources/templates/azure-eventhub-binder/application.properties, src/main/resources/templates/azure-redis-cache/application.properties, src/main/resources/templates/azure-storage/StorageController.java, src/main/resources/templates/azure-storage/application.properties, src/main/resources/templates/parent-pom.xml
=> Upgrade spring cloud azure module to 1.0.0.M2.

src/main/java/com/microsoft/azure/springcloudplayground/generator/ProjectGenerator.java, src/main/resources/templates/README.md
=> Add README to base dir, fix #166.

src/main/resources/static/js/start.js
* fix incorrect cache service
* load page status when page ready, load event may be blocked by other js file loading
=> Fix cache services (#173)

src/main/resources/application.yml
=> Reference link to M2 of spring-cloud-azure, fix #180

src/main/resources/application.yml
=> Merge devel tree to master for deployment

src/main/resources/static/css/customize.css, src/main/resources/templates/home.mustache
=> add preview badge

src/main/java/com/microsoft/azure/springcloudplayground/controller/MainController.java, src/main/java/com/microsoft/azure/springcloudplayground/module/ModuleNames.java
=> Align the schema of modules in use for BI.
